// Copyright (C) 2020  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and any partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details, at
// https://fpgasoftware.intel.com/eula.


// Generated by Quartus Prime Version 20.1 (Build Build 720 11/11/2020)
// Created on Sun May 22 20:07:02 2022

display_controller display_controller_inst
(
	.data(data_sig) ,	// output [7:0] data_sig
	.rs(rs_sig) ,	// output  rs_sig
	.rw(rw_sig) ,	// output  rw_sig
	.e(e_sig) ,	// output  e_sig
	.ascii_data(ascii_data_sig) ,	// input [7:0] ascii_data_sig
	.angle(angle_sig) ,	// input [11:0] angle_sig
	.write(write_sig) ,	// input  write_sig
	.clk(clk_sig) 	// input  clk_sig
);

